import type { Brief, CommandRuns, Conventions, IssueSnapshot } from "./jobs";
import type { Implemented } from "./implement";

export const branchFor = (issueNumber: number) => `agent/issue-${issueNumber}`;

/** The implement commit's subject, which is in the repo's commit style; without a style, Fix #N: <issue title>. */
export const prTitle = (issue: IssueSnapshot, conventions: Conventions, commitMessage: string) =>
  conventions.commit_style.trim() ? commitMessage.split("\n")[0]!.trim() : `Fix #${issue.number}: ${issue.title}`;

const runs = ({ runs, skipped }: CommandRuns, withBase: boolean) =>
  skipped
    ? `Skipped: ${skipped}.`
    : runs
        .map((r) => `- \`${r.command}\`${withBase ? (r.on === "base" ? " on the base with the new tests" : " on the change") : ""}: exit ${r.exit_code}`)
        .join("\n");

/** A fixed body rendered from the phases' data. */
export function prBody(p: {
  issue: IssueSnapshot;
  brief: Brief;
  implemented: Implemented;
  redGreen: CommandRuns;
  checks: CommandRuns;
  harness: string;
}) {
  const tests = p.implemented.tests_added.map((t) => `- \`${t.file}\`: ${t.name}`).join("\n") || "None: the repo has no tests.";
  return `Closes #${p.issue.number}

## Summary

${p.implemented.summary}

## Acceptance criteria

${p.brief.acceptance_criteria.map((c) => `- [ ] ${c}`).join("\n")}

## Seams

${p.brief.seams.map((s) => `- ${s}`).join("\n")}

## Tests added

${tests}

## Red/green

${runs(p.redGreen, true)}

## Checks

${runs(p.checks, false)}

---

AI-generated by auto-solve with ${p.harness}. Review it like any other change before merging.
`;
}
